### ISSUE TITLE
gitkeep问题

### ISSUE THREAD

**Issue by sunguangran** [xiongxianzhu/qingmi#18]
老铁，好多文件夹都是gitkeep，能否一起分享出来，学习下

**Comment by xiongxianzhu** [comment]
.gitkeep是占位作用的， 表示那个目录下暂时没有东西， 只是方便git commit和git push的时候能将空目录上传到github， 那几个用.gitkeep的目录暂时还没有完善的呢， 加上最近比较忙， 以后会慢慢完善呢

**Comment by sunguangran** [comment]
好的，多谢了,学习下

**Comment by xiongxianzhu** [comment]
好的， 有问题可以提出来一起交流
